FROM python:3.10

WORKDIR /02

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY subhashkumar_module7_2.py .

EXPOSE 8501

CMD ["streamlit", "run", "subhashkumar_module7_2.py", "--server.address=0.0.0.0"]