FROM python:3.10-slim

WORKDIR /06

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY subhashkumar_module7_6.py .

EXPOSE 8501

CMD [
    "streamlit",
    "run",
    "subhashkumar_module7_6.py",
    "--server.address=0.0.0.0"
]